version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "comments-database"
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - fullstack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    container_name: "comments-rest-api"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      SSL_MODE: disable
      DB_DB: postgres
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fullstack
    

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge